version: '3'
services:
  php:
    build: docker/php
    expose:
      - '9000'
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/abouevent
      - ./docker/logs/php:/var/log
  web:
    build: docker/nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - php
      - db
    volumes:
      - ./:/var/www/html/abouevent
      - ./docker/logs/nginx:/var/log/nginx
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=abou_event
      - MYSQL_USER=aboudevent
      - MYSQL_PASSWORD=abouevent_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./docker/mysql:/var/lib/mysql
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "25:25"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      - PMA_HOST=db
